---
- hosts: all
  sudo: true
  roles:
    - geerlingguy.repo-epel
  vars:
     packages: [ 'ntp','yum-cron' ]
  tasks:
    - name: set timezone
      timezone: name=Asia/Kuwait
    
    - name: install needed packages
      yum: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: update all packages
      yum: name=* state=latest

    - name: enable ntpd
      service: name=ntpd enabled=yes

    - name: enable ntpd
      service: name=ntpd state=started

    - name: enable yum-cron
      service: name=ntpd enabled=yes

    - name: enable yum-cron
      service: name=ntpd state=started
      
